### PR TITLE
Adding plotting of MT solutions

### PR DESCRIPTION
**Pull request by cebirnie92**

### CODE REVIEW

**Comment by cebirnie92** [comment]
Hi @danikiev now I added thumbnails I noticed the mt tutorial could benefit from using our mt visualisation functions. This should be my last push before the first release

**Comment by danikiev** [comment]
> Hi @danikiev now I added thumbnails I noticed the mt tutorial could benefit from using our mt visualisation functions. This should be my last push before the first release

Hi, good idea. I can't see the pictures now, but it is good to add.

 Few comments not related to mt visualisation, but other tutorials (sorry should have commented it in previous PR):

For `1_2_Detection_DiffractionStacking_tutorial.py` we are using `# sphinx_gallery_thumbnail_number = 6` in the beginning, this is what I would prefer , but later in the same block `# sphinx_gallery_thumbnail_number = 4` is used which is overriding it, can you please fix?

Then in `3_1_MT_AmplitudeInversion_tutorial.py` you are using another colorscheme for waveforms (second picture)?
Should we have default seismic as `RdBu`?

**Comment by cebirnie92** [comment]
> RdBu

Actually, all the other tutorials for waveforms are seismic, which is why I made the same for 3_2

**Comment by danikiev** [comment]
What I mean is these two colorschemes in 3_1:
Screenshot 2024-10-11 114923

**Review by danikiev — APPROVED** [review]
I am fine with the tutorials now, thanks. The color scheme in 3_1 is a minor thing

**Comment by cebirnie92** [comment]
> I am fine with the tutorials now, thanks. The color scheme in 3_1 is a minor thing

Oh sorry, I read your feedback to fast. Thanks for adding the screenshot. I have fixed it to be consistent

**Pull request merged**
