### PR TITLE
Detection ds

### PR DESCRIPTION
**Pull request by danikiev**
Finalizes the detection by diffraction stacking

### CODE REVIEW

**Comment by cebirnie92** [comment]
Hi @danikiev, there are quite a  few conflicts regarding the tutorials, mostly at a documentation level. Can you please perform a local merge with the master and accept the changes you wish (to resolve the conflicts) and then push again the branch.
Thanks

**Comment by danikiev** [comment]
> Hi @danikiev, there are quite a few conflicts regarding the tutorials, mostly at a documentation level. Can you please perform a local merge with the master and accept the changes you wish (to resolve the conflicts) and then push again the branch. Thanks

Sure, will do

**Comment by danikiev** [comment]
Fixed the conflicts. @cebirnie92 Claire please review

**Review by cebirnie92 — APPROVED** [review]
Changes look good - thank you

**Pull request merged**
