### PR TITLE
XC-based Imaging Refactor

### PR DESCRIPTION
**Pull request by cebirnie92**
- [x] Move XCI functions to imaging.py
- [x] Update location class to point to the right location
- [x] Check XCI function still works
- [ ] Write XCI tutorial with the SOFI FD data

### CODE REVIEW

**Comment by mrava87** [comment]
Done :) but I also had to fix a merge conflict, please take a look at all changes and make sure you agree before merging

**Review by mrava87 — APPROVED** [review]

**Comment by danikiev** [comment]
> Not sure why, the documentation is failing... let me take a look

```
Unexpected failing examples (1):
285

286
    ../../tutorials/Location_CrossCorrelationImaging_tutorial.py failed leaving traceback:
287

288
    Traceback (most recent call last):
289
      File "/home/runner/work/FraCSPy/FraCSPy/tutorials/Location_CrossCorrelationImaging_tutorial.py", line 201, in <module>
290
        xc_inv, xci_hc = L.apply(vz, kind="xcorri", Op=Op, nforhc=10)
291
      File "/home/runner/work/FraCSPy/FraCSPy/fracspy/location/location.py", line 73, in apply
292
        im, hc = _location_kind[kind](data, self.n_xyz, **kwargs)
293
    ValueError: too many values to unpack (expected 2)
```

It has something to do with the `xcorri` function that outputs 4, and we take from it only 2... Had the same issue in one of the worked examples

**Comment by mrava87** [comment]
@danikiev this is fixed and had to do with different numbers of outputs for the different methods.

Btw, I made some small adaptations to your `diffstack` method and the `Location` class to re-instate what I had initially planned for those high-level classes, namely that all methods called will be called with the same number and order of mandatory paramters followed by as many optional parameters as neeeded. Otherwise, starting to go down the if..elif..elif....else route would make this design a bit useless in that any new contributor would need to start going into the apply method and change it instead of simply i) making a new algorithm, ii) registering it into the `_location_kind` variable :)

**Comment by danikiev** [comment]
> @danikiev this is fixed and had to do with different numbers of outputs for the different methods.
> 
> Btw, I made some small adaptations to your `diffstack` method and the `Location` class to re-instate what I had initially planned for those high-level classes, namely that all methods called will be called with the same number and order of mandatory paramters followed by as many optional parameters as neeeded. Otherwise, starting to go down the if..elif..elif....else route would make this design a bit useless in that any new contributor would need to start going into the apply method and change it instead of simply i) making a new algorithm, ii) registering it into the `_location_kind` variable :)

I see, yes, my initial thinking was that since we already send x,y,z verctors as arguments to Location class, why would we send them again to diffstack. But that's OK - I agree with your changes, let us keep the initial idea ;)

**Comment by mrava87** [comment]
@cebirnie92 I think this is good to go, at least from my side

**Comment by mrava87** [comment]
Yes, I see your point too. For the algorithms that Claire implemented everything is already encaspulated in the `Op` but for you since you don't really do any upfront work I see why you need everything passed... let me think and see if we can do something that does not require providing things redundantly :)

**Pull request merged**
