### PR TITLE
Detection Matched Filtering

### PR DESCRIPTION
**Pull request by omarmohamed15**
**Template Preparation Script**

- Prepares templates for seismic event detection.
- Reads event times from a catalog and extracts corresponding data from continuous seismic recordings.
- Saves the extracted templates in a structured format for further analysis.

**Matched Filtering Using Correlation Script**

- Performs matched filtering to detect seismic events.
- Correlates the extracted templates with continuous seismic data.
- Identifies significant correlations and stores results for detailed analysis.

**Picks Association Script**

- Associates detected events with picks from seismic data.

**Example Plotting**

- Includes an example that visualizes associated events.

### CODE REVIEW

**Comment by danikiev** [comment]
Great job @omarmohamed15 !

Regarding the problem, it looks like there is a problem with loading the initial xlsx while creating docs.
Can we replace it with a csv? That would be much easier...
Also, does this catalog exist in the web, somewhere in TOC2ME github? We could download it in the runtime maybe, like we do it in toc2me worked examples?

Like this, here it is done for the one from Eaton et al 2018:

```python
# Provide URL for the catalogue
catalogue_url = 'https://github.com/ToC2ME/ToC2ME/blob/master/Eaton/Catalog_Eaton2018_SRL.csv?raw=true'

# File path to save the .mat file
catalogue_file= os.path.normpath(os.path.join(datafolder, 'Catalog_Eaton2018_SRL.csv')).replace('\\', '/')

# Download the file
response = requests.get(catalogue_url)

# Check if the request was successful
if response.status_code == 200:
    # Write the content to a file in binary mode
    with open(catalogue_file, 'wb') as file:
        file.write(response.content)
    
    print(f"File was successfully downloaded and saved to {catalogue_file}")
else:
    print("Failed to download the file. Status code:", response.status_code)
```

**Comment by cebirnie92** [comment]
> Great job @omarmohamed15 !
> 
> Regarding the problem, it looks like there is a problem with loading the initial xlsx while creating docs. Can we replace it with a csv? That would be much easier... Also, does this catalog exist in the web, somewhere in TOC2ME github? We could download it in the runtime maybe, like we do it in toc2me worked examples?
> 
> Like this, here it is done for the one from Eaton et al 2018:
> 
> ```python
> # Provide URL for the catalogue
> catalogue_url = 'https://github.com/ToC2ME/ToC2ME/blob/master/Eaton/Catalog_Eaton2018_SRL.csv?raw=true'
> 
> # File path to save the .mat file
> catalogue_file= os.path.normpath(os.path.join(datafolder, 'Catalog_Eaton2018_SRL.csv')).replace('\\', '/')
> 
> # Download the file
> response = requests.get(catalogue_url)
> 
> # Check if the request was successful
> if response.status_code == 200:
>     # Write the content to a file in binary mode
>     with open(catalogue_file, 'wb') as file:
>         file.write(response.content)
>     
>     print(f"File was successfully downloaded and saved to {catalogue_file}")
> else:
>     print("Failed to download the file. Status code:", response.status_code)
> ```

I agree with this, can we try to load directly from the web if possible as opposed to having static files.

**Comment by cebirnie92** [comment]
I think before we agreed to only have 1 tutorial for the template matching, not the 3 different stages separated, and then the separated stages are to go in the ToC2ME specific repository. I shall work on condensing the tutorials to only one, where it highlights only the fracspy function

**Comment by omarmohamed15** [comment]
> Great job @omarmohamed15 !
> 
> Regarding the problem, it looks like there is a problem with loading the initial xlsx while creating docs. Can we replace it with a csv? That would be much easier... Also, does this catalog exist in the web, somewhere in TOC2ME github? We could download it in the runtime maybe, like we do it in toc2me worked examples?
> 
> Like this, here it is done for the one from Eaton et al 2018:
> 
> ```python
> # Provide URL for the catalogue
> catalogue_url = 'https://github.com/ToC2ME/ToC2ME/blob/master/Eaton/Catalog_Eaton2018_SRL.csv?raw=true'
> 
> # File path to save the .mat file
> catalogue_file= os.path.normpath(os.path.join(datafolder, 'Catalog_Eaton2018_SRL.csv')).replace('\\', '/')
> 
> # Download the file
> response = requests.get(catalogue_url)
> 
> # Check if the request was successful
> if response.status_code == 200:
>     # Write the content to a file in binary mode
>     with open(catalogue_file, 'wb') as file:
>         file.write(response.content)
>     
>     print(f"File was successfully downloaded and saved to {catalogue_file}")
> else:
>     print("Failed to download the file. Status code:", response.status_code)
> ```

Okay, I will try to do that. 

Thanks, Denis!

**Comment by omarmohamed15** [comment]
> I think before we agreed to only have 1 tutorial for the template matching, not the 3 different stages separated, and then the separated stages are to go in the ToC2ME specific repository. I shall work on condensing the tutorials to only one, where it highlights only the fracspy function

I can consolidate all three steps into one, but we must start with the first step: preparing the template. Without this initial step, the subsequent steps won't function properly.

**Pull request closed without merging**
