### PR TITLE
Detection Tutorial Update

### PR DESCRIPTION
**Pull request by cebirnie92**
Updated detection tutorial to:

- [ ] load data from IRIS
- [ ] only load data once
- [ ] keep data/results in memory as opposed to writing to file and then reading in again within the same tutorial

Resulted in a few updates to the functions to remove the reading/writing elements

### CODE REVIEW

**Comment by cebirnie92** [comment]
@mrava87 and @danikiev I see the above build threw the error:
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

But I didn't think I added anything that required openpyxl. Any thoughts?

**Comment by danikiev** [comment]
> @mrava87 and @danikiev I see the above build threw the error: ImportError: Missing optional dependency 'openpyxl'. Use pip or conda to install openpyxl.
> 
> But I didn't think I added anything that required openpyxl. Any thoughts?

I think @omarmohamed15  is using xlsx catalog file because it is originally in Excel... 
So we kind of need somethig that reads xlsx or converts it to csv.

options are:

0. stay with `openpyxl`
it was complaining about some outdated version of it though

1. `pip install xlsx2csv`
```python
from xlsx2csv import Xlsx2csv

# Path to the input .xlsx file and output .csv file
xlsx_file = 'input_file.xlsx'
csv_file = 'output_file.csv'

# Convert the Excel file to CSV
Xlsx2csv(xlsx_file, outputencoding="utf-8").convert(csv_file)

print(f"{xlsx_file} has been converted to {csv_file}")
```

2. `pip install xlrd`

```python
import pandas as pd

# Path to the input .xls file and output .csv file
xls_file = 'input_file.xls'
csv_file = 'output_file.csv'

# Read the Excel file with xlrd engine (works only for .xls files)
df = pd.read_excel(xls_file, engine='xlrd')

# Save the DataFrame to a CSV file
df.to_csv(csv_file, index=False)

print(f"{xls_file} has been converted to {csv_file}")
```

**Comment by omarmohamed15** [comment]
> 1. openpyxl

I added "openpyxl" to the package dependencies in the toml file. Let's see if that could work.

**Comment by danikiev** [comment]
> > 1. openpyxl
> 
> I added "openpyxl" to the package dependencies in the toml file. Let's see if that could work.

Please also add to `requirements-dev.txt` and `environment-dev.yml`

**Comment by omarmohamed15** [comment]
> > > 1. openpyxl
> > 
> > 
> > I added "openpyxl" to the package dependencies in the toml file. Let's see if that could work.
> 
> Please also add to `requirements-dev.txt` and `environment-dev.yml`

@danikiev I did. The building went fine without error. 
@cebirnie92 I removed the script that plotted the detected associated events from the "Example" folder. How will we add it in the current stage without uploading files?

**Comment by danikiev** [comment]
Looks good, I think we can merge, @cebirnie92 ?

**Comment by cebirnie92** [comment]
Merging to bring up-to-date. I will make a new PR related to the examples. I think we can do it with written events detected. I just need 30 mins to figure it our

**Pull request merged**
